import os
import sqlite3

from fabric.api import *

DB_FILE = os.path.dirname(os.path.dirname(__file__)) + '/resources/db/hosts.db'

env.warn_only = True
env.skip_bad_hosts = True
env.use_ssh_config = True
env.ssh_config_path = os.path.dirname(os.path.dirname(__file__)) + '/resources/ssh/config_planetlab'

env.hosts = ['ple2.planet-lab.eu', 'dschinni.planetlab.extranet.uni-passau.de', 'iraplab2.iralab.uni-karlsruhe.de',
             'iraplab1.iralab.uni-karlsruhe.de', 'planetlab-1.ing.unimo.it', 'nuc1.planet-lab.eu', 'ple2.cesnet.cz',
             'pl221nassau0.cs.princeton.edu', 'planetlab2.sfc.wide.ad.jp', 'planet2.scs.cs.nyu.edu',
             'planetlab2.iii.u-tokyo.ac.jp', 'ricepl-1.cs.rice.edu', 'pl1.eecs.utk.edu', 'pl2.eecs.utk.edu',
             'planetlab1.cs.ubc.ca', 'plab1.cs.ust.hk', 'planetlab-2.scie.uestc.edu.cn', 'planetlab1.cs.umass.edu',
             'planetlab2.cs.umass.edu', 'planetlab1.iii.u-tokyo.ac.jp', 'planetlab-1.cs.colostate.edu',
             'planetlab3.cs.uchicago.edu', 'planetlab1.eecs.northwestern.edu', 'planetlab1.postel.org',
             'planetlab2.eecs.northwestern.edu', 'planetlab1.poly.edu', 'planetlab1.eee.hku.hk', 'pl1.csl.utoronto.ca',
             'planetlab2.eee.hku.hk', 'planetlab-1.cmcl.cs.cmu.edu', 'planetlab-2.cmcl.cs.cmu.edu',
             'planetlab2.cs.duke.edu', 'planet2.scs.stanford.edu', 'planetlab2.csres.utexas.edu',
             'planetlab-5.eecs.cwru.edu', 'planetlab1.cs.cornell.edu', 'plnode01.cs.mu.oz.au', 'plnode02.cs.mu.oz.au',
             'planetlab1.dtc.umn.edu', 'planetlab2.netlab.uky.edu', 'lefthand.eecs.harvard.edu',
             'righthand.eecs.harvard.edu', 'planetlab1.csres.utexas.edu', 'planetlab3.csres.utexas.edu',
             'planet1.cc.gt.atl.ga.us', 'planetlab2.cis.upenn.edu', 'planetlab01.uncc.edu', 'ricepl-2.cs.rice.edu',
             'planetlab1.cis.upenn.edu', 'kupl2.ittc.ku.edu', 'planetlab01.erin.utoronto.ca',
             'planetlab02.erin.utoronto.ca', 'planetlab1.eecs.umich.edu', 'planetlab2.eecs.umich.edu',
             'kupl1.ittc.ku.edu', 'planetlab1.cs.columbia.edu', 'planetlab2.cs.columbia.edu',
             'planetlab3.cs.columbia.edu', 'plink.cs.uwaterloo.ca', 'planetlab1.cs.uiuc.edu',
             'planetlab2.engr.uconn.edu', 'planetlab1.koganei.itrc.net', 'planetlab2.koganei.itrc.net',
             'newbootcd.cs.princeton.edu', 'f20bootcd.cs.princeton.edu', 'planetlab3.singaren.net.sg',
             'planetx.scs.cs.nyu.edu', 'planetlab1.pop-ce.rnp.br', 'planetlab1.pop-rs.rnp.br',
             'planetlab0.ias.csusb.edu', 'plab2.cs.ust.hk', 'orbpl1.rutgers.edu', 'orbpl2.rutgers.edu',
             'planet-lab1.cs.ucr.edu', 'planetlab3.georgetown.edu', 'planetlab4.georgetown.edu',
             'planetlab1.iis.sinica.edu.tw', 'planetlab2.iis.sinica.edu.tw', 'planetlab-1.cse.ohio-state.edu',
             'planetlab-2.cse.ohio-state.edu', 'planetlab1.netmedia.gist.ac.kr', 'planetlab1.cs.uchicago.edu',
             'planetlab2.cs.uchicago.edu', 'planetlab2.cs.purdue.edu', 'planetlab2.cnds.jhu.edu',
             'planetlab2.netmedia.gist.ac.kr', 'pli1-pa-1.hpl.hp.com', 'pli1-pa-2.hpl.hp.com', 'pli1-pa-3.hpl.hp.com',
             'pl1.cs.unm.edu', 'planetlab2.utep.edu', 'pl2-higashi.ics.es.osaka-u.ac.jp', 'planetlab1.cse.msu.edu',
             'planetlab-1a.ics.uci.edu', 'planetlab2.cse.msu.edu', 'planetlab1.uc.edu', 'planetlab-01.ece.uprm.edu',
             'planetlab-02.ece.uprm.edu', 'planetlab4.cs.uiuc.edu', 'planetlab1.pop-mg.rnp.br',
             'planetlab2.pop-mg.rnp.br', 'planetlab-2a.ics.uci.edu', 'planet0.jaist.ac.jp', 'planet1.jaist.ac.jp',
             'planetlab02.cs.washington.edu', 'planetlab2.uc.edu', 'planetlab-1.vuse.vanderbilt.edu',
             'planetlab-2.vuse.vanderbilt.edu', 'server2.planetlab.iit-tech.net', 'planetlab-1.usask.ca',
             'planetlab-2.usask.ca', 'planetlab2.cs.cornell.edu', 'planetlab1.eecs.wsu.edu', 'planetlab2.eecs.wsu.edu',
             'planetlab1.sfc.wide.ad.jp', 'planetlab3.csail.mit.edu', 'planetlab1.cesnet.cz',
             'planetlab04.cs.washington.edu', 'planetlab2.cesnet.cz', 'kc-sce-plab1.umkc.edu', 'kc-sce-plab2.umkc.edu',
             'planetlab3.netmedia.gist.ac.kr', 'planetlab1.ucsd.edu', 'planetlab2.ucsd.edu', 'planetlab3.ucsd.edu',
             'pl3.sos.info.hiroshima-cu.ac.jp', 'pl4.sos.info.hiroshima-cu.ac.jp', 'planetlab2.piotrkow.rd.tp.pl',
             'planetlab1.piotrkow.rd.tp.pl', 'csplanetlab3.kaist.ac.kr', 'plab1.engr.sjsu.edu', 'plab2.engr.sjsu.edu',
             'planet2.cc.gt.atl.ga.us', 'planet3.cc.gt.atl.ga.us', 'planet4.cc.gt.atl.ga.us',
             'planetlab0.otemachi.wide.ad.jp', 'planetlab1.otemachi.wide.ad.jp', 'planetlab0.dojima.wide.ad.jp',
             'planetlab1.dojima.wide.ad.jp', 'planetlab1.swidnik.rd.tp.pl', 'planetlab1.ias.csusb.edu',
             'planetlab2.singaren.net.sg', 'planetlab7.csail.mit.edu', 'planetlab4.csail.mit.edu',
             'planetlab-01.kusa.ac.jp', 'planetlab-02.kusa.ac.jp', 'planetlab1.emich.edu', 'planetlab2.emich.edu',
             'planetlab1.iin-bit.com.cn', 'fobos.cecalc.ula.ve', 'planetlab1.gdansk.rd.tp.pl',
             'planetlab2.gdansk.rd.tp.pl', 'planetlab1.nowogrodzka.rd.tp.pl', 'planetlab5.cs.duke.edu',
             'deimos.cecalc.ula.ve', 'planetlab2.nowogrodzka.rd.tp.pl', 'planetlab5.cs.cornell.edu',
             'planetlab6.cs.cornell.edu', 'planetlab4.ie.cuhk.edu.hk', 'planetlab2.tudelft.nl',
             'planetlab5.ie.cuhk.edu.hk', 'planetlab-03.naist.jp', 'planetlab-04.naist.jp', 'pllab2.kamgu.ru',
             'planetlab2.cs.ubc.ca', 'planetlab2.inf.ethz.ch', 'planetlab3.mini.pw.edu.pl', 'planetlab4.mini.pw.edu.pl',
             'planetlab2.eas.asu.edu', 'planetlab1.eas.asu.edu', 'planetlab4.flux.utah.edu', 'planetlab5.flux.utah.edu',
             'planetlab02.uncc.edu', 'planetlab2.iin-bit.com.cn', 'pub1-s.ane.cmc.osaka-u.ac.jp',
             'pub2-s.ane.cmc.osaka-u.ac.jp', 'planetlab1.citadel.edu', 'planetlab2.citadel.edu',
             'planetlab3.inf.ethz.ch', 'planetlab4.inf.ethz.ch', 'planetlab1.arizona-gigapop.net',
             'planetlab1-santiago.lan.redclara.net', 'planetlab2-santiago.lan.redclara.net',
             'planetlab1-saopaulo.lan.redclara.net', 'planetlab2-saopaulo.lan.redclara.net',
             'planetlabnode-1.docomolabs-usa.com', 'planetlabnode-2.docomolabs-usa.com',
             'planetlab2-buenosaires.lan.redclara.net', 'planetlab1-tijuana.lan.redclara.net',
             'planetlab2-tijuana.lan.redclara.net', 'pl1snu.koren.kr', 'planetlab-05.cs.princeton.edu',
             'planetlab2.byu.edu', 'mercury.silicon-valley.ru', 'venus.silicon-valley.ru', 'plab-1.sinp.msu.ru',
             'plab-2.sinp.msu.ru', 'planetlabb.engr.ccny.cuny.edu', 'planetlab3.piotrkow.rd.tp.pl', 'pllab1.kamgu.ru',
             'planetlab-02.bu.edu', 'planetlab01.lums.edu.pk', 'planetlab02.lums.edu.pk', 'pli1-pa-5.hpl.hp.com',
             'planetlab1.eecs.ucf.edu', 'planetlab2.eecs.ucf.edu', 'planetlab4.warsaw.rd.tp.pl',
             'planetlab1.williams.edu', 'planetlab2.williams.edu', 'planetlab3.williams.edu', 'planetlab1.nileu.edu.eg',
             'planetlab2.lublin.rd.tp.pl', 'planetlab1.lublin.rd.tp.pl', 'pl4.planetlab.uvic.ca',
             'pluto.cs.binghamton.edu', 'planetlab02.sys.virginia.edu', 'pl1.planetlab.uvic.ca',
             'pl3.planetlab.uvic.ca', 'planetlab1.comp.nus.edu.sg', 'planetlab2.comp.nus.edu.sg', 'saturn.cs.brown.edu',
             'jupiter.cs.brown.edu', 'pluto.cs.brown.edu', 'planetlab1.iitr.ernet.in', 'node01.verivue.princeton.edu',
             'planetlabone.ccs.neu.edu', 'planet-lab1.ufabc.edu.br', 'planet-lab2.ufabc.edu.br',
             'planetlab2.cs.unc.edu', 'mtuplanetlab1.cs.mtu.edu', 'planet3.cs.ucsb.edu', 'planetlab1.cs.uoregon.edu',
             'planetlab15.millennium.berkeley.edu', 'planetlab16.millennium.berkeley.edu', 'planetlab2.cs.umb.edu',
             'planetlab2.dtc.umn.edu', 'pl1.bit.uoit.ca', 'pl2.bit.uoit.ca', 'planetlab1.n.info.eng.osaka-cu.ac.jp',
             'plgmu2.ite.gmu.edu', 'planet1.ku.edu.tr', 'planet2.ku.edu.tr', 'cs-planetlab3.cs.surrey.sfu.ca',
             'planetlab1.csie.nuk.edu.tw', 'planetlab2.csie.nuk.edu.tw', 'planetlab3.csee.usf.edu',
             'pl1.ucs.indiana.edu', 'pl2.ucs.indiana.edu', 'planetlab1.cs.umb.edu',
             'planetlab2.n.info.eng.osaka-cu.ac.jp', 'cs-planetlab4.cs.surrey.sfu.ca', 'planetlab5.csres.utexas.edu',
             'planetlab4.csee.usf.edu', 'netapp6.cs.kookmin.ac.kr', 'netapp7.cs.kookmin.ac.kr',
             'planetlab3.eecs.northwestern.edu', 'planetlab1.buaa.edu.cn', 'node1.planetlab.mathcs.emory.edu',
             'planetlab4.williams.edu', 'planetlab5.williams.edu', 'planetslug4.cse.ucsc.edu',
             'planetslug5.cse.ucsc.edu', 'plab1.larc.usp.br', 'planetlab3.cse.nd.edu', 'planetlab4.cse.nd.edu',
             'node2.planetlab.mathcs.emory.edu', 'planetlab6.flux.utah.edu', 'planetlab7.flux.utah.edu',
             'planetlab2.arizona-gigapop.net', 'mtuplanetlab2.cs.mtu.edu', 'planetlab4.eecs.umich.edu',
             'planetlab3.wail.wisc.edu', 'planetlab4.wail.wisc.edu', 'planet-lab1.itba.edu.ar', 'planetlab1.unl.edu',
             'planetlab2.unl.edu', 'planetlab3.comp.nus.edu.sg', 'planetlab2.utdallas.edu', 'planet-lab2.cs.ucr.edu',
             'server3.planetlab.iit-tech.net', 'nis-planet1.doshisha.ac.jp', 'nis-planet2.doshisha.ac.jp',
             'planetlab1.csee.usf.edu', 'planetlab-2.calpoly-netlab.net', 'planetlab3.postel.org',
             'planetlab4.postel.org', 'plab3.eece.ksu.edu', 'planet-lab1.uba.ar', 'planet-lab2.itba.edu.ar',
             'vn5.cse.wustl.edu', 'plonk.cs.uwaterloo.ca', 'planetlab1.c3sl.ufpr.br', 'planetlab2.c3sl.ufpr.br',
             'planetlab2.cs.otago.ac.nz', 'planetlab1.cs.ucl.ac.uk', 'planetlab2.cs.ucl.ac.uk',
             'planetlab2.csee.usf.edu', 'planetlab9.millennium.berkeley.edu', 'node1.planetlab.albany.edu',
             'node2.planetlab.albany.edu', 'roam1.cs.ou.edu', 'roam2.cs.ou.edu', 'planetlab1.cs.otago.ac.nz',
             'node1.planet-lab.titech.ac.jp', 'node3.planet-lab.titech.ac.jp', 'node4.planet-lab.titech.ac.jp',
             'pl1.cewit.stonybrook.edu', 'pl2.cewit.stonybrook.edu', 'charon.cs.binghamton.edu',
             'pl1.planet.cs.kent.edu', 'osiris.planetlab.cs.umd.edu', 'whitefall.planetlab.cs.umd.edu',
             'pl2.planet.cs.kent.edu', 'planetlab2.poly.edu', 'planet-lab2.uba.ar', 'pn1-planetlab.huawei.com',
             'pn2-planetlab.huawei.com', 'planetlab3.n.info.eng.osaka-cu.ac.jp', 'planetlab-01.cs.princeton.edu',
             'planetlab-02.cs.princeton.edu', 'planetlab-03.cs.princeton.edu', 'planetlab-04.cs.princeton.edu',
             'planetlab1.ntu.nodes.planet-lab.org', 'planetlab01.cs.washington.edu', 'planetlab-1.cs.auckland.ac.nz',
             'planetlab-2.cs.auckland.ac.nz', 'pl1.rcc.uottawa.ca', 'planetlab4.n.info.eng.osaka-cu.ac.jp',
             'pl2.rcc.uottawa.ca', 'planetlab2.nileu.edu.eg', 'planetlab1.utep.edu', 'plab4.eece.ksu.edu',
             'planetlab6.goto.info.waseda.ac.jp', 'planetlab03.cs.washington.edu', 'pl1-higashi.ics.es.osaka-u.ac.jp',
             'planetlab3.cs.uiuc.edu', 'salt.planetlab.cs.umd.edu', 'planetlab2.csuohio.edu', 'planetlab1.csuohio.edu',
             'planetlab-1.cs.uic.edu', 'planetlab-2.cs.uic.edu', 'plnodea.plaust.edu.cn', 'flow.colgate.edu',
             'node0.planetlab.etl.luc.edu', 'node1.planetlab.etl.luc.edu', 'planetlab-2.webedu.ccu.edu.tw',
             'planetlab-01.vt.nodes.planet-lab.org', 'planetlab-02.vt.nodes.planet-lab.org', 'metis.mcs.suffolk.edu',
             'adrastea.mcs.suffolk.edu', 'planetlab4.cs.uoregon.edu', 'planetlab2.cs.uoregon.edu',
             'planet4.cs.ucsb.edu', 'planetlab2.ece.ucdavis.edu', 'planetlab1.cs.ucla.edu',
             'planetlab12.millennium.berkeley.edu', 'planetlab5.millennium.berkeley.edu',
             'planetlab13.millennium.berkeley.edu', 'planetlab-1.sjtu.edu.cn', 'planetlab-2.sjtu.edu.cn',
             'planetlab6.millennium.berkeley.edu', 'planetlab7.millennium.berkeley.edu',
             'planetlab10.millennium.berkeley.edu', 'planetlab11.millennium.berkeley.edu', 'planetlab1.just.edu.jo',
             'planetlab1.bgu.ac.il', 'planetlab2.bgu.ac.il', 'vn4.cse.wustl.edu', 'planetlab6.cs.duke.edu',
             'planetlab2.ntu.nodes.planet-lab.org', 'planetlab7.cs.duke.edu', 'planet11.csc.ncsu.edu',
             'planetlab5.eecs.umich.edu', 'planet12.csc.ncsu.edu', 'ebb.colgate.edu', 'planetlab5.cs.uiuc.edu',
             'planetlab6.cs.uiuc.edu', 'pl1.pku.edu.cn', 'mnc1.pusan.ac.kr', 'mnc2.pusan.ac.kr',
             'planetlab-3.ics.uci.edu', 'planetlab1.keldysh.ru', 'pl2snu.koren.kr',
             'planetlab-03.vt.nodes.planet-lab.org', 'planetlab-04.vt.nodes.planet-lab.org',
             'planetlab2.plab.ege.edu.tr', 'planetlab05.cs.washington.edu', 'planetlab06.cs.washington.edu',
             'nw144.csie.ncu.edu.tw', 'planetslug7.cse.ucsc.edu', 'planetlab2.cs.colorado.edu',
             'planetlab5.csee.usf.edu', 'planetlab2.keldysh.ru', 'planetlab-4.eecs.cwru.edu', 'pl1.eng.monash.edu.au',
             'planetlab3.cnds.jhu.edu', 'planetlab4.cnds.jhu.edu', 'pl2.eng.monash.edu.au',
             'planetlab4.cs.uchicago.edu', 'pl3.planet.cs.kent.edu', 'planetlab-6.ece.iastate.edu',
             'pl1.sos.info.hiroshima-cu.ac.jp', 'pl-node-0.csl.sri.com', 'planetlab-2.pdl.nudt.edu.cn',
             'planetlab-1.pdl.nudt.edu.cn', 'plgmu3.ite.gmu.edu', 'planetlab1.cs.dartmouth.edu',
             'planetlab2.cs.dartmouth.edu', 'planetlab2.uta.edu', 'pli1-pa-6.hpl.hp.com', 'planetlab6.csres.utexas.edu',
             'planetlab7.csres.utexas.edu', 'ricepl-4.cs.rice.edu', 'ricepl-5.cs.rice.edu',
             'planetlab1.cs.colorado.edu', 'pnode2.pdcc-ntu.singaren.net.sg', 'pl2.pku.edu.cn', 'planetlab1.simula.no',
             'pnode1.pdcc-ntu.singaren.net.sg', 'nodeb.howard.edu', 'planetlab02.just.edu.jo', 'plgmu5.ite.gmu.edu',
             'planetlab1.ecs.vuw.ac.nz', 'planetlab2.ecs.vuw.ac.nz', 'planet5.cs.ucsb.edu', 'planet6.cs.ucsb.edu',
             'plnode-03.gpolab.bbn.com', 'plnode-04.gpolab.bbn.com', 'server1.planetlab.iit-tech.net',
             'planetlab2.pop-pa.rnp.br', 'planetlab1.ece.ucdavis.edu', 'planetlab4.canterbury.ac.nz',
             'planetlab2.cs.stevens-tech.edu', 'planetlab1.cs.stevens-tech.edu', 'planetlab2.tamu.edu',
             'planetlab1.pop-pa.rnp.br', 'planetlab2.cs.uml.edu', 'planetlab1.cs.uml.edu', 'planetlab6.csee.usf.edu',
             'planetlab-n2.wand.net.nz', 'planet-plc-3.mpi-sws.org', 'planetlab2.clemson.edu',
             'planet-plc-4.mpi-sws.org', 'planetlab-2.elisa.cpsc.ucalgary.ca', 'pl1.6test.edu.cn', 'pl2.6test.edu.cn',
             'planetlab3.rutgers.edu', 'planetlab4.rutgers.edu', 'planetlab1.jhu.edu', 'planetlab2.jhu.edu',
             'planetlab4.netmedia.gist.ac.kr', 'ttu1-1.nodes.planet-lab.org', 'ttu2-1.nodes.planet-lab.org',
             'planetlab1.ustc.edu.cn', 'planetlab1.bupt.edu.cn', 'planetlab2.bupt.edu.cn',
             'pl2.sos.info.hiroshima-cu.ac.jp', 'planetlab2.cse.nd.edu', 'of-planet5.stanford.edu',
             'planet2.pnl.nitech.ac.jp', 'planet1.dsp.ac.cn', 'planet2.dsp.ac.cn', 'planetlab2.aut.ac.nz',
             'pl2.cs.yale.edu', 'pl1.cs.yale.edu', 'pl1.cis.uab.edu', 'planetlab-1.sysu.edu.cn',
             'planetlab-2.sysu.edu.cn', 'planet2.cs.rochester.edu', 'pl2.cis.uab.edu', 'planetlab2.cnis.nyit.edu',
             'pl-dccd-01.cua.uam.mx', 'server4.planetlab.iit-tech.net', 'arari.snu.ac.kr', 'recall.snu.ac.kr',
             'planetlab1.tsuniv.edu', 'planetlab-5.ece.iastate.edu', 'planetlab2.buaa.edu.cn', 'planetlab2.tsuniv.edu',
             'planetlab1.ie.cuhk.edu.hk', 'planet-lab4.uba.ar', 'planetlab3.tamu.edu', 'planetlab4.tamu.edu',
             'planetlab1.umassd.edu', 'planetlab2.umassd.edu', 'planetlab2.ustc.edu.cn', 'pl01.comp.polyu.edu.hk',
             'planetlab0.ucsc.cmb.ac.lk', 'planetlab1.ucsc.cmb.ac.lk', 'saturn.planetlab.carleton.ca',
             'planetlab1.unr.edu', 'planetlab4.bupt.edu.cn', 'jupiter.planetlab.carleton.ca', 'planetlab1.hust.edu.cn',
             'planetlab2.hust.edu.cn', 'planetlab-js2.cert.org.cn', 'planetlab3.bupt.edu.cn',
             'planetlab2.cti.espol.edu.ec', '75-130-96-12.static.oxfr.ma.charter.com',
             '75-130-96-13.static.oxfr.ma.charter.com', 'pl02.comp.polyu.edu.hk', 'planetlab2.cqupt.edu.cn',
             'planetlab1.cqupt.edu.cn', 'pln.zju.edu.cn', 'planetlab1.nakao-lab.org', 'planetlab2.nakao-lab.org',
             'plab1.cs.msu.ru', 'plab3.cs.msu.ru', 'planetlab1.iitkgp.ac.in', 'planetlab2.iitkgp.ac.in',
             'pl2.zju.edu.cn', 'planetlab2.cs.okstate.edu', 'planetlab2.rutgers.edu', 'planetlab1.pop-rj.rnp.br',
             'planetlab2.pop-rj.rnp.br', 'planetlab1.temple.edu', 'planetlab2.temple.edu', 'planetlab-js1.cert.org.cn',
             'planetlab-1.scie.uestc.edu.cn', 'pl2.cs.unm.edu', 'pl3.cs.unm.edu', 'pl4.cs.unm.edu',
             'pl1.cs.montana.edu', 'planetlab2.iitr.ernet.in', 'planetlab-1.ece.iastate.edu',
             'planetlab02.alucloud.com', 'planetlab01.alucloud.com', 'plnodeb.plaust.edu.cn',
             'planetlab1.mnlab.cti.depaul.edu', 'planetlab1.cs.unc.edu', 'planetlab2.een.orst.edu',
             'planetlab1.een.orst.edu', 'node02.verivue.princeton.edu', 'planetlab3.arizona-gigapop.net',
             'planet-plc-1.mpi-sws.org', 'planet-plc-2.mpi-sws.org', 'planetlab-2.ece.iastate.edu',
             'planet-plc-6.mpi-sws.org', 'planetlab3.canterbury.ac.nz', 'planetlab1.cs.du.edu', 'planetlab2.cs.du.edu',
             'planet-lab3.uba.ar', 'planetlab-1.elisa.cpsc.ucalgary.ca', 'planetlab1.engr.uconn.edu',
             'planetlab-3.ece.iastate.edu', 'planetlab3.cesnet.cz', 'planetlab1.acis.ufl.edu',
             'planetlab1.cs.wayne.edu', 'planetlab1.inf.ethz.ch', 'planetlab1.cs.pitt.edu', 'planetlab2.unr.edu',
             'pl1.yonsei.ac.kr', 'pl2.yonsei.ac.kr', 'planetlab2.ie.cuhk.edu.hk', 'planetlab2.cs.wayne.edu',
             'planetlab-n1.wand.net.nz', 'plgmu1.ite.gmu.edu', 'planetlab1.warsaw.rd.tp.pl', 'nw142.csie.ncu.edu.tw',
             'planetlab-01.naist.jp', 'planetlab-02.naist.jp', 'planetlab1.ewi.tudelft.nl', 'planetlab2.ewi.tudelft.nl',
             'planetlabtwo.ccs.neu.edu', 'planetlab-2.ssvl.kth.se', 'planetlab3.millennium.berkeley.edu',
             'planetlab1.millennium.berkeley.edu', 'planetlab2.millennium.berkeley.edu', 'planetlab2.olsztyn.rd.tp.pl',
             'planet1.scs.cs.nyu.edu', 'planet1.scs.stanford.edu', 'planetlab-2.cs.colostate.edu',
             'pl2.csl.utoronto.ca', 'planetlab-3.cmcl.cs.cmu.edu', 'pli1-pa-4.hpl.hp.com', 'planetlab1.netlab.uky.edu',
             'plab2.nec-labs.com', 'plab1.nec-labs.com', 'planetlab1.rutgers.edu', 'planetlab1.byu.edu',
             'planetlab2.cs.uiuc.edu', 'planetlab2.pop-rs.rnp.br', 'planetlab1.cs.purdue.edu',
             'planetlab1.cnds.jhu.edu', 'planetlab1.cse.nd.edu', 'planetlab1.tamu.edu', 'planetlab1.uta.edu',
             'csplanetlab4.kaist.ac.kr', 'planetlab1.singaren.net.sg', 'planetlab5.csail.mit.edu',
             'planetlab4.cs.duke.edu', 'planetlab1.tudelft.nl', 'planetlab6.csail.mit.edu',
             'planetlab1-buenosaires.lan.redclara.net', 'planetlab2.postel.org', 'planetlab-01.bu.edu',
             'planetlab01.sys.virginia.edu', 'earth.cs.brown.edu', 'pl-dccd-02.cua.uam.mx', 'planetlab2.pop-ce.rnp.br',
             'planetlab4.csres.utexas.edu', 'plab2.larc.usp.br', 'planetlab1.utdallas.edu',
             'planetlab-1.calpoly-netlab.net', 'planetlab14.millennium.berkeley.edu', 'planetlab3.eecs.umich.edu',
             'planetlab5.goto.info.waseda.ac.jp', 'planetlab4.singaren.net.sg', 'planetlab-1.webedu.ccu.edu.tw',
             'planetlab3.cs.uoregon.edu', 'planetlab2.cs.ucla.edu', 'planetlab4.millennium.berkeley.edu',
             'planetlab8.millennium.berkeley.edu', 'planetlab1.plab.ege.edu.tr', 'pl-node-1.csl.sri.com',
             'plgmu4.ite.gmu.edu', 'miranda.planetlab.cs.umd.edu', 'nodea.howard.edu', 'planet1.cs.rochester.edu',
             'planetlab1.clemson.edu', 'planet1.pnl.nitech.ac.jp', 'planetlab1.aut.ac.nz', 'planetlab1.cnis.nyit.edu',
             'planetlab-4.ece.iastate.edu', 'planetlab4.goto.info.waseda.ac.jp', 'planetlab1.cti.espol.edu.ec',
             'planetlab1.cs.okstate.edu', 'pl2.cs.montana.edu', 'planet-plc-5.mpi-sws.org', 'planetlab2.acis.ufl.edu',
             'planetlab2.cs.pitt.edu', 'planetlab-1.ssvl.kth.se', 'planetlab2.mnlab.cti.depaul.edu',
             'ple41.planet-lab.eu', 'ple43.planet-lab.eu', 'ple1.cesnet.cz', 'ple42.planet-lab.eu',
             'netissime1.planet-lab.eu', 'ple1.planet-lab.eu', 'aladdin.planetlab.extranet.uni-passau.de',
             'onelab2.pl.sophia.inria.fr', 'ple44.planet-lab.eu', 'stella.planetlab.ntua.gr', 'kulcha.mimuw.edu.pl',
             'planet3.cs.huji.ac.il', 'planetlab11.net.in.tum.de', 'planet-lab-node2.netgroup.uniroma2.it',
             'planetvs2.informatik.uni-stuttgart.de', 'dplanet1.uoc.edu', 'planetlab-2.ing.unimo.it',
             'planetlab1.cs.uit.no', 'planetlab2.upm.ro', 'puri.mimuw.edu.pl', 'vicky.planetlab.ntua.gr',
             'netissime2.planet-lab.eu', 'planet4.cs.huji.ac.il', 'planetlab1.upm.ro', 'planetlab13.net.in.tum.de',
             'planetlab-2.cs.ucy.ac.cy', 'planetlab1.informatik.uni-goettingen.de',
             'planetlab2.informatik.uni-goettingen.de']

conn = sqlite3.connect(DB_FILE)
c = conn.cursor()
c.execute('CREATE TABLE hosts {host VARCHAR(255) PRIMARY KEY};')
conn.commit()
c.close()
conn.close()


@parallel(pool_size=6)
def host_type():
    run('uname -a')
    conn_local = sqlite3.connect(DB_FILE)
    c_local = conn.cursor()
    c_local.execute("insert into hosts values '{}'".format(env.host))
    conn_local.commit()
    c_local.close()
    conn_local.close()
