all:
  pre:
  apt:
  - tmux
  - vim
  - openvswitch-switch
  - pkg-config
  - iputils-ping
  post:
balancer:
  pre:
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
  apt:
  - mysql-server
  - libmysqlclient-dev
  post:
  - sudo service mysql start
server:
  pre:
  apt:
  post:
