all:
  pre:
  apt:
  - tmux
  - vim
  - openvswitch-switch
  - pkg-config
  - iputils-ping
  post:
  - sudo service openvswitch-switch start
balancer:
  pre:
  - echo 'ROLE=balancer' >> ~/env
#  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
#  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
  apt:
  - mysql-client
#  - mysql-server
  - libmysqlclient-dev
  post:
#  - sudo service mysql start
server:
  pre:
  - echo 'ROLE=server' >> ~/env
  apt:
  post:
