all:
  pre:
  apt:
  - tmux
  - vim
  - openvswitch-switch
  - pkg-config
  - iputils-ping
  - libev-dev
  - zsh
  post:
  - sudo service openvswitch-switch start
  - chsh -s `which zsh` johnson
  - wget -q https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true
balancer:
  pre:
  - echo 'ROLE=balancer' >> ~/env
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
  apt:
  - mysql-client
  - mysql-server
  - python3-dev
  - python3-pip
  - libmysqlclient-dev
  post:
  - sudo service mysql start
  - sudo pip3 install mysqlclient
server:
  pre:
  - echo 'ROLE=server' >> ~/env
  apt:
  post:
db:
  pre:
  - echo 123

