all:
  pre:
  apt:
  - tmux
  - vim
  - openvswitch-switch
  - pkg-config
balancer:
  pre:
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
  apt:
  - mysql-server
  - libmysqlclient-dev
server:
  pre:
  apt:
