# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

  config.vm.define "balancer1" do |balancer1|
    balancer1.vm.hostname = "balancer1"
    balancer1.vm.network "private_network", ip: "170.16.156.100"
    balancer1.vm.network "private_network", ip: "173.16.156.100"
  end

  config.vm.define "balancer5" do |balancer5|
    balancer5.vm.hostname = "balancer5"
    balancer5.vm.network "private_network", ip: "170.16.156.150"
    balancer5.vm.network "private_network", ip: "173.16.156.150"
  end

  config.vm.define "server11" do |server11|
    server11.vm.hostname = "server11"
    server11.vm.network "private_network", ip: "173.16.156.101"
  end

  config.vm.define "server51" do |server51|
    server51.vm.hostname = "server51"
    server51.vm.network "private_network", ip: "173.16.156.151"
  end

  config.vm.define "server12" do |server12|
    server12.vm.hostname = "server12"
    server12.vm.network "private_network", ip: "173.16.156.102"
  end

  config.vm.define "server52" do |server52|
    server52.vm.hostname = "server52"
    server52.vm.network "private_network", ip: "173.16.156.152"
  end

  config.vm.synced_folder "../../scripts", "/home/vagrant/app/scripts"
  config.vm.synced_folder "../../bin", "/home/vagrant/app/bin"
  config.vm.synced_folder "../../keys", "/home/vagrant/app/keys"
  config.vm.synced_folder "../../hestia/exec", "/home/vagrant/app/hestia/exec"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -qq
    sudo apt-get install -y -qq net-tools openssh-server sudo zsh git vim
    sudo useradd -m johnson && echo "johnson:johnson" | chpasswd && adduser johnson sudo
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
    chsh -s `which zsh` johnson
    sudo su johnson -c 'mkdir /home/johnson/.ssh'
    sudo su johnson -c 'echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVcYOl/Q/TkpxdA4GYbVda8flEQ3EDTaNoBMzYHQ/owPYXP/vaAT3DL3Lxgs12eslNA9px8wqNckmdUdc0NsUyh8Od1ke2S+FCkC/b2tK75aZ3PQsGJb0z+hdYu1/kFby5WKllTQRgNkvkOhTOWu+ybFeiCrylShMXXrkdC6aBQ8w7qWyaGlr1CBs+cKxAd2zyuYn3E5KiyhJPFZr+hN8EH6Q0wtAwTec8ViosY7pEcdIkBl1RUvwiZdaCv5fnGoax62dzQO7jCTVdBAH3jQifBsMLaLffGKqGjF926DLFwhEpUEKL4B/I3LNehAbV+xDnIkFchucgjNkmXamv5yl7W5PVgdyl3W7SoxKfVut0/0eKUKjRplZrhKVCRNLKqnHA9C3yF8QAYRwhlAOwFarEAi5zJNJV+JniFpNkXCsXdJxuZukHPDVJlY8LVyopxbvjSGTowlwgIoCtJPWbW15nioo0Sm1exVJff50eG6L8oTbFTCIar2YcXz07skqmW1nqE53bEBgqageSsjOcBouS8f7X3xOC66qQB1Oyyi9+gUJF4O6NpLlhFvyJMER3Yl4v89LyqAUi27FGbcn+zzCKELV5zjHTmJ+18EOPYv8h7IIJ4nR31QCD4F1eW1TRt4fXn8oEW/H9H+ItcDKQwSn39ZyK/q1t8hYDV1rzavv59w== johnsonli1993@gmail.com" > /home/johnson/.ssh/authorized_keys'
    sudo su johnson -c 'wget -q https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true'
    sudo su johnson -c 'ln -s /home/vagrant/app /home/johnson/app'
    sudo su johnson -c "echo 'export PATH=$PATH:/sbin' >> /home/johnson/.zshrc"
    echo 'export interface=enp0s9'| sudo tee -a /etc/environment > /dev/null
  SHELL
end
